{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "my-nginx-chart.labels" . | nindent 4 }}
    {{- if .Values.namespace.istioInjection }}
    istio-injection: enabled
    {{- end }}
{{- end }}