apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/zyusuke10/my-istio-app-gitops.git
    targetRevision: master
    path: application-manifests/nginx-app/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: my-nginx-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true